{{
    config(
        materialized="incremental",
        schema="silver_noaa",
        unique_key=["__row_hash"],
        incremental_strategy='merge' if target.name == 'bigquery' else 'delete+insert',
        tags=["det_catchup"],
    )
}}

-- generated by det scaffold-dbt; silver identity/order from pipeline dbt.silver
with stg_filtered as (
    select *
    from {{ ref("stg_noaa__storm_events") }}
    {{ det_silver_incremental_filter(
        watermark="__extract_run_datetime",
        unique_key=["__row_hash"],
        pipeline_name="noaa.storm_events",
        lookback=none
    ) }}
),
{{ det_silver_catchup_guard(
    watermark="__extract_run_datetime",
    unique_key=["__row_hash"],
    pipeline_name="noaa.storm_events"
) }},
deduped as (
    {{ det_dedupe_latest_run(
        "base",
        partition_by=["__row_hash"],
        order_by=["__extract_run_datetime desc"]
    ) }}
)
select
    deduped.*,
    current_timestamp as __silver_processed_at,
    current_timestamp as __silver_updated_at
from deduped
