{{
    config(
        materialized="view"
    )
}}

-- generated by det scaffold-dbt; relation silver for line_items
with base as (
    select *
    from {{ ref("stg_example_api__orders__line_items") }}
)

{{ det_dedupe_latest_run(
    "base",
    partition_by=["id", "__rel_index"],
    order_by=["__extract_run_datetime desc"]
) }}
