{{
    config(
        materialized="incremental",
        schema="silver_noaa",
        unique_key=["__row_hash"],
        incremental_strategy="delete+insert",
    )
}}

-- generated by det scaffold-dbt; silver identity/order from pipeline dbt.silver
with base as (
    select *
    from {{ ref("stg_noaa__storm_events") }}
    {% if is_incremental() %}
    where __extract_run_datetime > (
        select coalesce(max(__extract_run_datetime), '0001-01-01')
        from {{ this }}
    )
    {% endif %}
),
deduped as (
    {{ det_dedupe_latest_run(
        "base",
        partition_by=["__row_hash"],
        order_by=["__extract_run_datetime desc"]
    ) }}
)
select
    deduped.*,
    current_timestamp as __silver_processed_at,
    current_timestamp as __silver_updated_at
from deduped
