{{
    config(
        materialized="view"
    )
}}

-- generated by det scaffold-dbt; relation silver for line_items__tax_lines
with base as (
    select *
    from {{ ref("stg_example_api__orders__line_items__tax_lines") }}
)

{{ det_dedupe_latest_run(
    "base",
    partition_by=["id", "__rel_index_0", "__rel_index_1"],
    order_by=["__extract_run_datetime desc"]
) }}
