{{
    config(
        materialized="table",
        schema="silver_example_api",
    )
}}

-- generated by det scaffold-dbt; silver identity/order from pipeline dbt.silver
with stg_filtered as (
    select *
    from {{ ref("stg_example_api__events") }}
),
base as (
    select * from stg_filtered
),
deduped as (
    {{ det_dedupe_latest_run(
        "base",
        partition_by=["__row_hash"],
        order_by=["__extract_run_datetime desc"]
    ) }}
)
select
    deduped.*,
    current_timestamp as __silver_processed_at,
    current_timestamp as __silver_updated_at
from deduped
