{{
    config(
        materialized="view"
    )
}}

-- generated by det scaffold-dbt; relation silver for discount_codes
with base as (
    select *
    from {{ ref("stg_example_api__orders__discount_codes") }}
)

{{ det_dedupe_latest_run(
    "base",
    partition_by=["id", "__rel_index"],
    order_by=["__extract_run_datetime desc"]
) }}
