{{
    config(
        materialized="table",
        schema="silver_example_api",
    )
}}

-- generated by det scaffold-dbt; silver identity/order from pipeline dbt.silver
with base as (
    select *
    from {{ ref("stg_example_api__events") }}
)

{{ det_dedupe_latest_run(
    "base",
    partition_by=["__row_hash"],
    order_by=["__extract_run_datetime desc"]
) }}
