{{
    config(
        materialized="table",
    )
}}

-- generated by det scaffold-dbt; silver identity/order from pipeline dbt.silver
with base as (
    select *
    from {{ ref("stg_example_api__orders") }}
)

{{ det_dedupe_latest_run(
    "base",
    partition_by=["id"],
    order_by=["__extract_run_datetime desc"]
) }}
