{{
    config(
        materialized="view",
        schema="silver_noaa"
    )
}}

-- generated by det scaffold-dbt; edit for domain cleaning, or re-run with --force
-- to refresh the column list from the pipeline schema.
select
{{ det_as_integer('episode_id') }} as episode_id,
{{ det_as_integer('event_id') }} as event_id,
{{ det_as_string('azimuth') }} as azimuth,
{{ det_as_integer('lat2') }} as lat2,
{{ det_as_double('latitude') }} as latitude,
{{ det_as_string('location') }} as location,
{{ det_as_integer('location_index') }} as location_index,
{{ det_as_integer('lon2') }} as lon2,
{{ det_as_double('longitude') }} as longitude,
{{ det_as_double('range') }} as range,
{{ det_as_integer('yearmonth') }} as yearmonth,
__row_hash,
__bronze_loaded_at,
__data_interval_date,
__extract_run_datetime,
__filename,
__interval_end_datetime,
__interval_start_datetime
from {{ det_bronze_from("locations_v1", "bronze_noaa") }}
