{{
    config(
        materialized="view",
        schema="silver_example_api"
    )
}}

-- generated by det scaffold-dbt; edit for domain cleaning, or re-run with --force
-- to refresh the column list from the pipeline schema.
select
{{ det_as_string('id') }} as id,
{{ det_as_string('email') }} as email,
{{ det_as_string('currency') }} as currency,
{{ det_as_string('status') }} as status,
discount_codes as discount_codes,
line_items as line_items,
{{ det_json_path_string('customer', '$.id') }} as customer__id,
{{ det_json_path_string('customer', '$.loyalty.tier.code') }} as customer__loyalty__tier__code,
{{ det_json_path_string('customer', '$.loyalty.tier.name') }} as customer__loyalty__tier__name,
{{ det_json_path_string('customer', '$.default_address.city') }} as customer__default_address__city,
{{ det_json_path_double('customer', '$.default_address.geo.coords.lat') }} as customer__default_address__geo__coords__lat,
{{ det_json_path_double('customer', '$.default_address.geo.coords.lon') }} as customer__default_address__geo__coords__lon,
{{ det_json_path_string('shipping_address', '$.city') }} as shipping_address__city,
{{ det_json_path_string('shipping_address', '$.country_code') }} as shipping_address__country_code,
{{ det_json_path_double('shipping_address', '$.geo.coords.lat') }} as shipping_address__geo__coords__lat,
{{ det_json_path_double('shipping_address', '$.geo.coords.lon') }} as shipping_address__geo__coords__lon,
{{ det_json_path_double('shipping_address', '$.geo.accuracy_m') }} as shipping_address__geo__accuracy_m,
__row_hash,
__filename,
__extract_run_datetime,
__bronze_loaded_at,
__interval_start_datetime,
__interval_end_datetime,
__data_interval_date
from {{ det_bronze_from("orders_v1", "bronze_example_api") }}
