{{
    config(
        materialized="view"
    )
}}

-- generated by det scaffold-dbt; relation line_items__tax_lines from line_items[]tax_lines[]
-- edit for domain cleaning, or re-run with --force to refresh from schema.
with exploded as (
    select
        _parent.id as id,
        t0.__rel_index as __rel_index_0,
        t1._rel as _rel,
        t1.__rel_index as __rel_index_1,
        _parent.__row_hash as __row_hash,
        _parent.__filename as __filename,
        _parent.__extract_run_datetime as __extract_run_datetime,
        _parent.__interval_start_datetime as __interval_start_datetime,
        _parent.__interval_end_datetime as __interval_end_datetime,
        _parent.__data_interval_date as __data_interval_date
    from {{ det_bronze_from("orders", "bronze_example_api") }} as _parent
    cross join unnest(cast(_parent.line_items as JSON[])) with ordinality as t0(_rel, __rel_index)
    cross join unnest(cast(json_extract(t0._rel, '$.tax_lines') as JSON[])) with ordinality as t1(_rel, __rel_index)
    where _parent.line_items is not null
)
select
{{ det_as_string('id') }} as id,
__rel_index_0,
__rel_index_1,
{{ det_json_path_string('_rel', '$.title') }} as title,
{{ det_json_path_double('_rel', '$.rate') }} as rate,
{{ det_json_path_string('_rel', '$.price_set.shop_money.amount') }} as price_set__shop_money__tax_amount,
{{ det_json_path_string('_rel', '$.price_set.shop_money.currency_code') }} as price_set__shop_money__currency_code,
__row_hash,
__filename,
__extract_run_datetime,
__interval_start_datetime,
__interval_end_datetime,
__data_interval_date
from exploded
