{{
    config(
        materialized="view",
        schema="silver_example_api"
    )
}}

-- generated by det scaffold-dbt; edit for domain cleaning, or re-run with --force
-- to refresh the column list from the pipeline schema.
select
{{ det_as_string('id') }} as id,
{{ det_as_string('occurred_at') }} as occurred_at,
coalesce({{ det_as_string('severity') }}, {{ det_as_string('severity_level') }}, {{ det_as_string('level') }}) as event_severity,
nullif(nullif(nullif({{ det_as_string('state') }}, ''), 'NA'), 'null') as state,
case when ({{ det_as_string('status') }}) = '1' then 'open' when ({{ det_as_string('status') }}) = '2' then 'closed' when ({{ det_as_string('status') }}) = '3' then 'archived' else ({{ det_as_string('status') }}) end as status,
__row_hash,
__filename,
__extract_run_datetime,
__bronze_loaded_at,
__interval_start_datetime,
__interval_end_datetime,
__data_interval_date
from {{ det_bronze_from("events", "bronze_example_api") }}
