{{
    config(
        materialized="view"
    )
}}

-- generated by det scaffold-dbt; edit for domain cleaning, or re-run with --force
-- to refresh the column list from the pipeline schema.
select
{{ det_as_string('id') }} as id,
nullif(nullif({{ det_as_string('email') }}, ''), 'NA') as email,
{{ det_as_string('currency') }} as currency,
case when ({{ det_as_string('status') }}) = '1' then 'open' when ({{ det_as_string('status') }}) = '2' then 'closed' else ({{ det_as_string('status') }}) end as status,
{{ det_json_path_string('customer', '$.id') }} as customer__id,
case when ({{ det_json_path_string('customer', '$.loyalty.tier.code') }}) = 'gold' then 'gold' when ({{ det_json_path_string('customer', '$.loyalty.tier.code') }}) = 'silver' then 'silver' else ({{ det_json_path_string('customer', '$.loyalty.tier.code') }}) end as customer__loyalty__tier__code,
{{ det_json_path_string('customer', '$.loyalty.tier.name') }} as customer__loyalty__tier__loyalty_tier,
{{ det_json_path_string('customer', '$.default_address.city') }} as customer__default_address__city,
{{ det_json_path_double('customer', '$.default_address.geo.coords.lat') }} as customer__default_address__geo__coords__lat,
{{ det_json_path_double('customer', '$.default_address.geo.coords.lon') }} as customer__default_address__geo__coords__lon,
nullif(nullif({{ det_json_path_string('shipping_address', '$.city') }}, ''), 'NA') as shipping_address__ship_city,
{{ det_json_path_string('shipping_address', '$.country_code') }} as shipping_address__country_code,
{{ det_json_path_double('shipping_address', '$.geo.coords.lat') }} as shipping_address__geo__coords__ship_lat,
{{ det_json_path_double('shipping_address', '$.geo.coords.lon') }} as shipping_address__geo__coords__ship_lon,
__row_hash,
__filename,
__extract_run_datetime,
__interval_start_datetime,
__interval_end_datetime,
__data_interval_date
from {{ det_bronze_from("orders", "bronze_example_api") }}
