{{
    config(
        materialized="view"
    )
}}

-- generated by det scaffold-dbt; relation line_items from line_items[]
-- edit for domain cleaning, or re-run with --force to refresh from schema.
with exploded as (
    select
        _parent.id as id,
        t0._rel as _rel,
        t0.__rel_index as __rel_index,
        _parent.__row_hash as __row_hash,
        _parent.__filename as __filename,
        _parent.__extract_run_datetime as __extract_run_datetime,
        _parent.__interval_start_datetime as __interval_start_datetime,
        _parent.__interval_end_datetime as __interval_end_datetime,
        _parent.__data_interval_date as __data_interval_date
    from {{ det_bronze_from("orders", "bronze_example_api") }} as _parent
    cross join unnest(cast(_parent.line_items as JSON[])) with ordinality as t0(_rel, __rel_index)
    where _parent.line_items is not null
)
select
{{ det_as_string('id') }} as id,
__rel_index,
{{ det_json_path_string('_rel', '$.sku') }} as line_sku,
{{ det_json_path_integer('_rel', '$.quantity') }} as quantity,
{{ det_json_path_string('_rel', '$.variant.id') }} as variant__id,
{{ det_json_path_string('_rel', '$.variant.product.id') }} as variant__product__id,
{{ det_json_path_string('_rel', '$.variant.product.category.id') }} as variant__product__category__id,
{{ det_json_path_string('_rel', '$.variant.product.category.name') }} as variant__product__category__category,
{{ det_json_path_string('_rel', '$.price_set.shop_money.amount') }} as price_set__shop_money__amount,
{{ det_json_path_string('_rel', '$.price_set.shop_money.currency_code') }} as price_set__shop_money__currency_code,
__row_hash,
__filename,
__extract_run_datetime,
__interval_start_datetime,
__interval_end_datetime,
__data_interval_date
from exploded
