{{
    config(
        materialized="view",
        schema="silver_openlibrary"
    )
}}

-- generated by det scaffold-dbt; edit for domain cleaning, or re-run with --force
-- to refresh the column list from the pipeline schema.
select
{{ det_as_string('cover_edition_key') }} as cover_edition_key,
{{ det_as_integer('cover_id') }} as cover_id,
{{ det_as_string('key') }} as key,
{{ det_as_string('subject_key') }} as subject_key,
authors as authors,
{{ det_json_path_string('availability', '$.__src__') }} as availability____src__,
{{ det_json_path_boolean('availability', '$.available_to_borrow') }} as availability__available_to_borrow,
{{ det_json_path_boolean('availability', '$.available_to_browse') }} as availability__available_to_browse,
{{ det_json_path_boolean('availability', '$.available_to_waitlist') }} as availability__available_to_waitlist,
{{ det_json_path_string('availability', '$.error_message') }} as availability__error_message,
{{ det_json_path_string('availability', '$.identifier') }} as availability__identifier,
{{ det_json_path_boolean('availability', '$.is_browseable') }} as availability__is_browseable,
{{ det_json_path_boolean('availability', '$.is_lendable') }} as availability__is_lendable,
{{ det_json_path_boolean('availability', '$.is_previewable') }} as availability__is_previewable,
{{ det_json_path_boolean('availability', '$.is_printdisabled') }} as availability__is_printdisabled,
{{ det_json_path_boolean('availability', '$.is_readable') }} as availability__is_readable,
{{ det_json_path_boolean('availability', '$.is_restricted') }} as availability__is_restricted,
{{ det_json_path_string('availability', '$.isbn') }} as availability__isbn,
{{ det_json_path_string('availability', '$.last_loan_date') }} as availability__last_loan_date,
{{ det_json_path_string('availability', '$.last_waitlist_date') }} as availability__last_waitlist_date,
{{ det_json_path_integer('availability', '$.num_waitlist') }} as availability__num_waitlist,
{{ det_json_path_string('availability', '$.oclc') }} as availability__oclc,
{{ det_json_path_string('availability', '$.openlibrary_edition') }} as availability__openlibrary_edition,
{{ det_json_path_string('availability', '$.openlibrary_work') }} as availability__openlibrary_work,
{{ det_json_path_string('availability', '$.status') }} as availability__status,
{{ det_as_integer('edition_count') }} as edition_count,
{{ det_as_integer('first_publish_year') }} as first_publish_year,
{{ det_as_boolean('has_fulltext') }} as has_fulltext,
{{ det_as_string('ia') }} as ia,
ia_collection as ia_collection,
{{ det_as_string('lending_edition') }} as lending_edition,
{{ det_as_string('lending_identifier') }} as lending_identifier,
{{ det_as_boolean('printdisabled') }} as printdisabled,
{{ det_as_boolean('public_scan') }} as public_scan,
subject as subject,
{{ det_as_string('title') }} as title,
__row_hash,
__bronze_loaded_at,
__data_interval_date,
__extract_run_datetime,
__filename,
__interval_end_datetime,
__interval_start_datetime
from {{ det_bronze_from("subjects_v1", "bronze_openlibrary") }}
