{{
    config(
        materialized="view",
        schema="silver_noaa"
    )
}}

-- generated by det scaffold-dbt; edit for domain cleaning, or re-run with --force
-- to refresh the column list from the pipeline schema.
select
{{ det_as_integer('fat_yearmonth') }} as fat_yearmonth,
{{ det_as_integer('fat_day') }} as fat_day,
{{ det_as_integer('fat_time') }} as fat_time,
{{ det_as_integer('fatality_id') }} as fatality_id,
{{ det_as_integer('event_id') }} as event_id,
{{ det_as_string('fatality_type') }} as fatality_type,
{{ det_as_string('fatality_date') }} as fatality_date,
{{ det_as_integer('fatality_age') }} as fatality_age,
{{ det_as_string('fatality_sex') }} as fatality_sex,
{{ det_as_string('fatality_location') }} as fatality_location,
__row_hash,
__filename,
__extract_run_datetime,
__interval_start_datetime,
__interval_end_datetime,
__data_interval_date
from {{ det_bronze_from("fatalities", "bronze_noaa") }}
