{{
    config(
        materialized="view"
    )
}}

-- generated by det scaffold-dbt; edit for domain cleaning, or re-run with --force
-- to refresh the column list from the pipeline schema.
select
fat_yearmonth,
fat_day,
fat_time,
fatality_id,
event_id,
nullif(trim(cast(fatality_type as varchar)), '') as fatality_type,
nullif(trim(cast(fatality_date as varchar)), '') as fatality_date,
fatality_age,
nullif(trim(cast(fatality_sex as varchar)), '') as fatality_sex,
nullif(trim(cast(fatality_location as varchar)), '') as fatality_location,
__row_hash,
__filename,
__extract_run_datetime,
__interval_start_datetime,
__interval_end_datetime,
__data_interval_date
from {{ det_bronze_from("fatalities") }}
